port: 8080
spring:
  boot:
    admin:
      context-path: /admin-server
  application:
    name: admin-server

management:
    endpoints:
      web:
        exposure:
          include: "*"
        base-path: /applications
endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
logging:
  config: classpath:log4j2-spring.xml