spring:
  config:
    import: env.properties
  application:
    name: shipper-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false #to disable contextual lob creation when application starts.
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    date-format: dd-MM-yyyy
    default-property-inclusion: non_null


server:
  port: ${SERVER_PORT}

upload:
  dir: ${UPLOAD_DIR}

default:
  image:
    path: ${DEFAULT_IMAGE_PATH}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    healthcheck:
      enabled: true

#this is for actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#        include: health, metrics, prometheus
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

#logging:
#  config: classpath:log4j2-spring.xml

feign:
  client:
    config:
      default:
        connectTimeout: 5000 #5 seconds
        readTimeout: 5000  #5 seconds
        loggerLevel: basic #basic, none, full

