spring:
  config:
    import: env.properties
  application:
    name: shipper-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}


  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT}

upload:
  dir: C:/Users/ShafagA/Downloads/GoTruck-Main/shipper-service/src/main/resources/static/images/ProfileImage/

default:
  image:
    path: ${DEFAULT_IMAGE_PATH}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    healthcheck:
      enabled: true

#this is for actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  config: classpath:log4j2-spring.xml

  boot:
  admin:
  client:
  url: http://localhost:8080

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b