# Application and Environment Configuration
spring:
  application:
    name: shipper-service
  config:
    import: env.properties

# Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

# JPA and Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

# Mail Configuration
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

# Jackson Configuration
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    default-property-inclusion: non_null

# Server Configuration
server:
  port: ${SERVER_PORT}

# Security Configuration
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

# Upload Configuration
upload:
  dir: ${UPLOAD_DIR}

# Default Image Configuration
default:
  image:
    path: ${DEFAULT_IMAGE_PATH}

# Eureka Client Configuration
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# Actuator Configuration
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000 #5 seconds
        readTimeout: 5000  #5 seconds
        loggerLevel: basic #basic, none, full

springdoc:
  swagger-ui:
    path: /swagger-ui.html