version: '3'

services:
  config-server:
    build:
      context: ./config-server
    ports:
      - "8088:8088"
    networks:
      - my_network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8060:8060"
    networks:
      - my_network

  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - my_network

  shipper-service:
    build:
      context: ./shipper-service
    ports:
      - "9091:9091"
    networks:
      - my_network

networks:
  my_network:
