version: '3'

services:

  config-server:
    container_name: gotruck_config_server
    image: gotruck/config-server:1.0
    build:
      context: ./config-server
    ports:
      - "8088:8088"
    networks:
      - my_network

  api-gateway:
    container_name: gotruck_api_gateway
    image: gotruck/api-gateway:1.0
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    networks:
      - my_network

  discovery-server:
    container_name: gotruck_discovery_server
    image: gotruck/discovery-server:1.0
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my_network

  shipper-service:
    container_name: gotruck_shipper_service
    image: gotruck/shipper-service:1.0
    build:
      context: ./shipper-service
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - my_network

  truck-category-service:
    container_name: gotruck_truck_category_service
    image: gotruck/truck-category-service:1.0
    build:
      context: ./truck-category-service
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    networks:
      - my_network

  order-service:
    container_name: gotruck_order_service
    image: gotruck/order-service:1.0
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "4044:4044"
    networks:
      - my_network

    # Prometheus
  prometheus:
      container_name: prometheus
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - ./monitoring/prometheus/config/prometheus.yml:/etc/monitoring/prometheus/config/prometheus.yml
      networks:
        - my_network

    # Grafana
  grafana:
      container_name: grafana
      image: grafana/grafana-oss:latest
      ports:
        - "3000:3000"
      environment:
        GH_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      networks:
        - my_network

networks:
  my_network:
    driver: bridge
