version: '3'

services:
  config-server:
    build:
      context: ./config-server
    ports:
      - "8088:8088"
    networks:
      - my_network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8060:8060"
    networks:
      - my_network

  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - my_network

  shipper-service:
    build:
      context: ./shipper-service
    ports:
      - "9091:9091"
    networks:
      - my_network

    # Prometheus
  prometheus:
      container_name: prometheus
      image: prom/prometheus:v2.40.0
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yaml
      networks:
        - my_network

    # Grafana
  grafana:
      container_name: grafana
      image: grafana/grafana-oss:latest
      ports:
        - "3000:3000"
      environment:
        GH_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      networks:
        - my_network

networks:
  my_network:
