version: '3'

services:

  config-server:
    build:
      context: ./config-server
    ports:
      - "8088:8088"
    networks:
      - my_network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8060:8060"
    networks:
      - my_network

  service-registry:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - my_network

  shipper-service:
    build:
      context: ./shipper-service
    ports:
      - "9091:9091"
    networks:
      - my_network

  truck-category-service:
    build:
      context: ./truck-category-service
    ports:
      - "9080:9080"
    networks:
      - my_network

  order-service:
    build:
      context: ./order-service
    ports:
      - "4044:4044"
    networks:
      - my_network

    # Prometheus
  prometheus:
      container_name: prometheus
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - ./monitoring/prometheus/config/prometheus.yml:/etc/monitoring/prometheus/config/prometheus.yml
      networks:
        - my_network

    # Grafana
  grafana:
      container_name: grafana
      image: grafana/grafana-oss:latest
      ports:
        - "3000:3000"
      environment:
        GH_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      networks:
        - my_network

networks:
  my_network:
