server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://loacalhost:8088"
  cloud:
    gateway:
      routes:
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking/**

        - id: shipper-service
          uri: lb://shipper-service
          predicates:
            - Path=/shipper/**

#        - id: config-server
#          uri: lb://localhost:8761
#          predicates:
#            - Path=/eureka/**
