server:
  port: 8060

logging:
  level:
    ROOT: INFO
    com.gotruck: DEBUG
    com.gotruck.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
#  config:
#    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: truck-category-service
          uri: lb://truck-category-service
          predicates:
            - Path=/api/v1/truck-names/**, /api/v1/truck-categories/**
          filters:
            - StripPrefix=2

        - id: shipper-service
          uri: lb://shipper-service
          predicates:
            - Path=/api/v1/**, api/v1/auth/**, api/v1/shipper/orders/**, api/v1/shipper-users/**
          filters:
            - StripPrefix=2

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2

#this is for eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    healthcheck:
      enabled: true

# this is for actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Bütün actuator endpointləri aktivdir
  tracing:
    sampling:
      probability: 1.0  # Bütün sorğular üçün tracing aktivdir

