server:
  port: 8060

logging:
  level:
    ROOT: INFO
    com.gotruck: DEBUG
    com.gotruck.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive
#  config:
#    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: truck-category-service
          uri: lb://truck-category-service
          predicates:
            - Path=/api/v1/truck-names/**, /api/v1/truck-categories/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: truckCategoryServiceCircuitBreaker
                fallbackUri: forward:/fallback/truckCategoryServiceFallback

        - id: shipper-service
          uri: lb://shipper-service
          predicates:
            - Path=/api/v1/**, api/v1/auth/**, api/v1/shipper/orders/**, api/v1/shipper-users/**
          filters:
            - StripPrefix=2

            - name: CircuitBreaker
              args:
                name: shipperServiceCircuitBreaker
                fallbackUri: forward:/fallback/shipperServiceFallback

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/orderServiceFallback

#this is for eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# this is for actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Bütün actuator endpointləri aktivdir
  tracing:
    sampling:
      probability: 1.0  # Bütün sorğular üçün tracing aktivdir

#openapi:
#  service:
#    title: Api Gateway Doc
#    version: 1.0.0
#    url: http://localhost:8060 #api gateway url

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: shipper-service
        url: http://localhost:9091/v3/api-docs
      - name: order-service
        url: http://localhost:4044/v3/api-docs
      - name: truck-category-service
        url: http://localhost:9080/v3/api-docs