spring:
  config:
    import: env.properties
  application:
    name: order-service

  # Liquibase configuration
  liquibase:
    change-log: liquibase/changelog-master.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

  # Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    date-format: dd-MM-yyyy HH:mm:ss

server:
  port: ${SERVER_PORT}

# Actuator configuration
management:
  # Tracing configuration
  tracing:
    sampling:
      probability: 1.0

  # Prometheus endpoint configuration
  endpoint:
    prometheus:
      enabled: true

  # Exposed endpoints configuration
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

  # Environment info configuration
  info:
    env:
      enabled: true

  # Metrics configuration
  metrics:
    export:
      prometheus:
        enabled: true

#this is for eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      getOrderById:
        # configs for close state
        sliding-window-type: count_based
        failure-rate-threshold: 50.0
        sliding-window-size: 10
        # configs for open state
        wait-duration-in-open-state: 10s
        # configs for hal-open state
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        max-wait-duration-in-half-open-state: 15000