# Application name and configuration import
spring:
  application:
    name: truck-category-service
  config:
    import: env.properties

  # MVC configuration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

  # Hibernate and JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Liquibase configuration
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

# Server configuration
server:
  port: ${SERVER_PORT}

# Application specific configurations
application:
  # Interceptor configuration
  interceptor:
    common-request:
      exclude-path-patterns: /swagger**/**,/**/api-docs,/error,/favicon.ico

  # Swagger configuration
  swagger:
    base-package: "com.gotruck.truckcategoryservice.controller"
    paths: "/.*"
    apiInfo:
      version: 1.0
      title: "Truck Category Rest API"
      description: "Spring Boot REST API for Truck Category"

  # Client configuration
  client:
    account:
      url: http://localhost:9080

# Eureka client configuration
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery-server:8761/eureka/}
    healthcheck:
      enabled: true

# Actuator configuration
management:
  # Tracing configuration
  tracing:
    sampling:
      probability: 1.0

  # Prometheus endpoint configuration
  endpoint:
    prometheus:
      enabled: true

  # Exposed endpoints configuration
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

  # Environment info configuration
  info:
    env:
      enabled: true

  # Metrics configuration
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    com.gotruck: DEBUG
    springfox: DEBUG

# Common swagger configuration
common:
  swagger:
    enabled: true

