# Application name and configuration import
spring:
  application:
    name: truck-category-service
  config:
    import: env.properties

  # Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

  # Hibernate and JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Liquibase configuration
  liquibase:
    change-log: liquibase/changelog-master.yml

# Server configuration
server:
  port: ${SERVER_PORT}

# Eureka client configuration
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# Actuator configuration
management:
  # Tracing configuration
  tracing:
    sampling:
      probability: 1.0

  # Prometheus endpoint configuration
  endpoint:
    prometheus:
      enabled: true

  # Exposed endpoints configuration
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

  # Environment info configuration
  info:
    env:
      enabled: true

  # Metrics configuration
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    com.gotruck: DEBUG

