spring:
  config:
    import: env.properties
  application:
    name: truck-category-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

  # Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: ${SERVER_PORT}


#this is for eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
       defaultZone: ${EUREKA_SERVER:http://discovery-server:8761/eureka/}
    healthcheck:
      enabled: true

#this is for actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    #        include: health, metrics, prometheus
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
